language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/

script:
  - pwd
  - ls /home/travis
  # Build public website
  - (cd public && bundle exec jekyll build)
  # Test links on public website
  # - (cd public && bundle exec htmlproofer ./_site) TODO reenable

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_deploy:
  - nvm install $(cat .nvmrc)
  - nvm use
  - npm i -g npm
  - npm i -g firebase-tools

deploy:
  - provider: script
    script: bash -c "npx firebase deploy --only hosting"
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master)$
